
// DB CONSTANTS
export { 
    CHARACTERISTIC_COAT_COLOR,

    REGISTRATION_TYPE_REGISTERED,

    ARTIFICIAL_INSEMINATION_FROZEN_LAPROSCOPIC,
    ARTIFICIAL_INSEMINATION_FROZEN_VAGINAL,
} from "./schema";