import { BirthParseRow } from '@app/api';

export const birthParseMap: Record<string, keyof BirthParseRow> = {
  BREEDER_ID: 'breederId',
  BREEDER_NAME: 'breederName',
  IS_STILLBORN: 'isStillborn',
  ANIMAL_NAME: 'animalName',
  SEX_KEY: 'sexKey',
  SEX: 'sex',
  BIRTHDATE: 'birthdate',
  BIRTH_TYPE_KEY: 'birthTypeKey',
  SIRE_ID: 'sireId',
  DAM_ID: 'damId',
  PREFIX_KEY: 'prefixKey',
  PREFIX: 'prefix',
  FED_TYPE_KEY: 'fedTypeKey',
  FED_TYPE: 'fedType',
  FED_COLOR_KEY: 'fedColorKey',
  FED_COLOR: 'fedColor',
  FED_LOC_KEY: 'fedLocKey',
  FED_LOC: 'fedLoc',
  FED_NUM: 'fedNum',
  FARM_TYPE_KEY: 'farmTypeKey',
  FARM_TYPE: 'farmType',
  FARM_COLOR_KEY: 'farmColorKey',
  FARM_COLOR: 'farmColor',
  FARM_LOC_KEY: 'farmLocKey',
  FARM_LOC: 'farmLoc',
  FARM_NUM: 'farmNum',
  WEIGHT: 'weight',
  WEIGHT_UNITS_KEY: 'weightUnitsKey',
  WEIGHT_UNITS: 'weightUnits',
  COAT_COLOR_TABLE_KEY: 'coatColorTableKey',
  COAT_COLOR_KEY: 'coatColorKey',
  COAT_COLOR: 'coatColor',
  CONCEPTION_TYPE_KEY: 'conceptionTypeKey',
  CONCEPTION_TYPE: 'conceptionType',
  BIRTH_NOTES: 'birthNotes',
};
