import { OwnerType } from "../owners/ownerType";

export type DefaultSettingsResults = {
  id: string;
  name: string;
  owner_id: string;
  owner_type: OwnerType;
  owner_id_premiseid: string | null;
  breeder_id_contactid: string | null;
  breeder_id_companyid: string | null;
  breeder_id_premiseid: string | null;
  vet_id_contactid: string | null;
  vet_id_premiseid: string | null;
  lab_id_companyid: string | null;
  lab_id_premiseid: string | null;
  id_registry_id_companyid: string | null;
  registry_id_premiseid: string | null;
  id_stateid: string | null;
  id_countyid: string | null;
  id_flockprefixid: string | null;
  id_speciesid: string | null;
  id_breedid: string | null;
  id_sexid: string | null;
  id_idtypeid_primary: string | null;
  id_idtypeid_secondary: string | null;
  id_idtypeid_tertiary: string | null;
  id_eid_tag_male_color_female_color_same: string;
  eid_tag_color_male: string;
  eid_tag_color_female: string;
  eid_tag_location: string;
  id_farm_tag_male_color_female_color_same: string;
  farm_tag_based_on_eid_tag: string;
  farm_tag_number_digits_from_eid: string;
  farm_tag_color_male: string;
  farm_tag_color_female: string;
  farm_tag_location: string;
  id_fed_tag_male_color_female_color_same: string;
  fed_tag_color_male: string;
  fed_tag_color_female: string;
  fed_tag_location: string;
  id_nues_tag_male_color_female_color_same: string;
  nues_tag_color_male: string;
  nues_tag_color_female: string;
  nues_tag_location: string;
  id_trich_tag_male_color_female_color_same: string;
  trich_tag_color_male: string;
  trich_tag_color_female: string;
  trich_tag_location: string;
  trich_tag_auto_increment: string;
  trich_tag_next_tag_number: string;
  id_bangs_tag_male_color_female_color_same: string;
  bangs_tag_color_male: string;
  bangs_tag_color_female: string;
  bangs_tag_location: string;
  id_sale_order_tag_male_color_female_color_same: string;
  sale_order_tag_color_male: string;
  sale_order_tag_color_female: string;
  sale_order_tag_location: string;
  use_paint_marks: string;
  paint_mark_color: string;
  paint_mark_location: string;
  tattoo_color: string;
  tattoo_location: string;
  freeze_brand_location: string;
  id_idremovereasonid: string | null;
  id_tissuesampletypeid: string | null;
  id_tissuetestid: string | null;
  id_tissuesamplecontainertypeid: string | null;
  birth_type: string;
  rear_type: string;
  minimum_birth_weight: number;
  maximum_birth_weight: number;
  birth_weight_id_unitsid: string;
  weight_id_unitsid: string | null;
  sale_price_id_unitsid: string | null;
  evaluation_update_alert: string;
  death_reason_id_contactid: string | null;
  death_reason_id_companyid: string | null;
  id_deathreasonid: string | null;
  transfer_reason_id_contactid: string | null;
  transfer_reason_id_companyid: string | null;
  id_transferreasonid: string | null;
}
