import { RegistrationParseRow } from '@app/api';

export const registrationParseMap: Record<string, keyof RegistrationParseRow> = {
  BREEDER_ID: 'breederId',
  BREEDER_NAME: 'breederName',
  ID_ANIMALID: 'animalId',
  REGISTRATION_NUMBER: 'registrationNumber',
  ANIMAL_PREFIX: 'animalPrefix',
  ANIMAL_NAME: 'animalName',
  BIRTHDATE: 'birthdate',
  SEX: 'sex',
  BIRTH_TYPE: 'birthType',
  IS_OFFICIAL: 'isOfficial',
  FED_TYPE_KEY: 'fedTypeKey',
  FED_TYPE: 'fedType',
  FED_COLOR_KEY: 'fedColorKey',
  FED_COLOR: 'fedColor',
  FED_LOC_KEY: 'fedLocKey',
  FED_LOC: 'fedLoc',
  FED_NUM: 'fedNum',
  FARM_TYPE_KEY: 'farmTypeKey',
  FARM_TYPE: 'farmType',
  FARM_COLOR_KEY: 'farmColorKey',
  FARM_COLOR: 'farmColor',
  FARM_LOC_KEY: 'farmLocKey',
  FARM_LOC: 'farmLoc',
  FARM_NUM: 'farmNum',
  COAT_COLOR_KEY: 'coatColorKey',
  COAT_COLOR: 'coatColor',
};
