import { AnimalTrakkerIPC } from "./apis";

export {
  AnimalIdentification,
  AnimalIdInfoInput,
  AnimalNote,
  AnimalRegistrationResult,
  AnimalRow,
  AnimalSearchRequest,
  AnimalSearchResult,
  BirthInfo,
  BirthType,
  BirthParseRow,
  BirthParseResponse,
  Breed,
  BreedRequest,
  CoatColor,
  CodonResponse,
  Color,
  Company,
  Contact,
  Country,
  County,
  DatabaseSessionInfo,
  DatabaseStateCheckResponse,
  DeathReason,
  DeathParseResponse,
  DeathParseRow,
  DefaultSettingsResults,
  DrugEvent,
  ExistingMemberBuyer,
  FlockPrefix,
  idTag,
  idType,
  idColor,
  idLocation,
  NewBuyer,
  ParseResult,
  Premise,
  RegistryType,
  RegistryProcessType,
  RegistryProcessRequest,
  RegistrationParseResponse,
  RemoveReason,
  SellerInfo,
  Sex,
  Species,
  State,
  TagLocation,
  TagType,
  TissueSampleContainerType,
  TissueSampleType,
  TissueTest,
  TransferReason,
  TransferParseResponse,
  Unit,
  UnitRequest,
  UnitType,
  NewDefaultSettingsParameters,
  PedigreeNode,
  ScrapieFlockInfo,
  ProcessingResult,
  RegistryRow,
  RegistryFieldDef,
  RegistrationWriteResponse,
  RegistrationParseRow,
  Owner,
  OwnerType,
  OwnerContact,
  OwnerCompany,
  TissueTestResult,
  ValidationResult,
  ValidationResponse
} from "./dtos";

export type {
  AnimalTrakkerIPC,
  SystemAPI,
  AnimalAPI,
  DefaultsAPI,
  ExportAPI,
  LookupAPI,
  RegistryAPI,
  StoreAPI
} from "./apis"

declare global {
  interface Window extends AnimalTrakkerIPC {}
}
