import { getDatabase } from "../../../dbConnections.js";
import { DefaultSettingsResults } from "../../../models/read/defaults/getExistingDefaults.js";

export const getExistingDefaults = async (): Promise<DefaultSettingsResults[]> => {
  const db = await getDatabase();
  if (db == null) {
    throw new TypeError("DB Instance is null");
  }

  let defaultsQuery = `
    SELECT 
      id_animaltrakkerdefaultsettingsid AS id, 
      default_settings_name AS name,

      owner_id_contactid,
      owner_id_companyid,
      owner_id_premiseid,
      breeder_id_contactid,
      breeder_id_companyid,
      breeder_id_premiseid,
      vet_id_contactid,
      vet_id_premiseid,
      lab_id_companyid,
      lab_id_premiseid,
      id_registry_id_companyid,
      registry_id_premiseid,
      id_stateid,
      id_countyid,
      id_flockprefixid,
      id_speciesid,
      id_breedid,
      id_sexid,
      id_idtypeid_primary,
      id_idtypeid_secondary,
      id_idtypeid_tertiary,
      
      id_eid_tag_male_color_female_color_same,
      eid_tag_color_male,
      eid_tag_color_female,
      eid_tag_location,
      id_farm_tag_male_color_female_color_same,
      farm_tag_based_on_eid_tag,
      farm_tag_number_digits_from_eid,
      farm_tag_color_male,
      farm_tag_color_female,
      farm_tag_location,
      id_fed_tag_male_color_female_color_same,
      fed_tag_color_male,
      fed_tag_color_female,
      fed_tag_location,
      id_nues_tag_male_color_female_color_same,
      nues_tag_color_male,
      nues_tag_color_female,
      nues_tag_location,
      id_trich_tag_male_color_female_color_same,
      trich_tag_color_male,
      trich_tag_color_female,
      trich_tag_location,
      trich_tag_auto_increment,
      trich_tag_next_tag_number,
      
      id_bangs_tag_male_color_female_color_same,
      bangs_tag_color_male,
      bangs_tag_color_female,
      bangs_tag_location,
      id_sale_order_tag_male_color_female_color_same,
      sale_order_tag_color_male,
      sale_order_tag_color_female,
      sale_order_tag_location,
      
      use_paint_marks,
      paint_mark_color,
      paint_mark_location,
      tattoo_color,
      tattoo_location,
      freeze_brand_location,
      
      id_idremovereasonid,
      id_tissuesampletypeid,
      id_tissuetestid,
      id_tissuesamplecontainertypeid,
      
      birth_type,
      rear_type,
      minimum_birth_weight,
      maximum_birth_weight,
      birth_weight_id_unitsid,
      weight_id_unitsid,
      sale_price_id_unitsid,
      
      evaluation_update_alert,
      
      death_reason_id_contactid,
      death_reason_id_companyid,
      id_deathreasonid,
      
      transfer_reason_id_contactid,
      transfer_reason_id_companyid,
      id_transferreasonid

    FROM animaltrakker_default_settings_table`;

  return new Promise((resolve, reject) => {
    db.all(defaultsQuery, [], (err, rows) => {
      if (err) {
        reject(err);
      } else {
        const results: DefaultSettingsResults[] = rows.map((row: any) => ({
          id: row.id,
          name: row.name,
          owner_id_contactid: row.owner_id_contactid,
          owner_id_companyid: row.owner_id_companyid,
          owner_id_premiseid: row.owner_id_premiseid,
          breeder_id_contactid: row.breeder_id_contactid,
          breeder_id_companyid: row.breeder_id_companyid,
          breeder_id_premiseid: row.breeder_id_premiseid,
          vet_id_contactid: row.vet_id_contactid,
          vet_id_premiseid: row.vet_id_premiseid,
          lab_id_companyid: row.lab_id_companyid,
          lab_id_premiseid: row.lab_id_premiseid,
          id_registry_id_companyid: row.id_registry_id_companyid,
          registry_id_premiseid: row.registry_id_premiseid,
          id_stateid: row.id_stateid,
          id_countyid: row.id_countyid,
          id_flockprefixid: row.id_flockprefixid,
          id_speciesid: row.id_speciesid,
          id_breedid: row.id_breedid,
          id_sexid: row.id_sexid,
          id_idtypeid_primary: row.id_idtypeid_primary,
          id_idtypeid_secondary: row.id_idtypeid_secondary,
          id_idtypeid_tertiary: row.id_idtypeid_tertiary,
          id_eid_tag_male_color_female_color_same: row.id_eid_tag_male_color_female_color_same,
          eid_tag_color_male: row.eid_tag_color_male,
          eid_tag_color_female: row.eid_tag_color_female,
          eid_tag_location: row.eid_tag_location,
          id_farm_tag_male_color_female_color_same: row.id_farm_tag_male_color_female_color_same,
          farm_tag_based_on_eid_tag: row.farm_tag_based_on_eid_tag,
          farm_tag_number_digits_from_eid: row.farm_tag_number_digits_from_eid,
          farm_tag_color_male: row.farm_tag_color_male,
          farm_tag_color_female: row.farm_tag_color_female,
          farm_tag_location: row.farm_tag_location,
          id_fed_tag_male_color_female_color_same: row.id_fed_tag_male_color_female_color_same,
          fed_tag_color_male: row.fed_tag_color_male,
          fed_tag_color_female: row.fed_tag_color_female,
          fed_tag_location: row.fed_tag_location,
          id_nues_tag_male_color_female_color_same: row.id_nues_tag_male_color_female_color_same,
          nues_tag_color_male: row.nues_tag_color_male,
          nues_tag_color_female: row.nues_tag_color_female,
          nues_tag_location: row.nues_tag_location,
          id_trich_tag_male_color_female_color_same: row.id_trich_tag_male_color_female_color_same,
          trich_tag_color_male: row.trich_tag_color_male,
          trich_tag_color_female: row.trich_tag_color_female,
          trich_tag_location: row.trich_tag_location,
          trich_tag_auto_increment: row.trich_tag_auto_increment,
          trich_tag_next_tag_number: row.trich_tag_next_tag_number,
          id_bangs_tag_male_color_female_color_same: row.id_bangs_tag_male_color_female_color_same,
          bangs_tag_color_male: row.bangs_tag_color_male,
          bangs_tag_color_female: row.bangs_tag_color_female,
          bangs_tag_location: row.bangs_tag_location,
          id_sale_order_tag_male_color_female_color_same: row.id_sale_order_tag_male_color_female_color_same,
          sale_order_tag_color_male: row.sale_order_tag_color_male,
          sale_order_tag_color_female: row.sale_order_tag_color_female,
          sale_order_tag_location: row.sale_order_tag_location,
          use_paint_marks: row.use_paint_marks,
          paint_mark_color: row.paint_mark_color,
          paint_mark_location: row.paint_mark_location,
          tattoo_color: row.tattoo_color,
          tattoo_location: row.tattoo_location,
          freeze_brand_location: row.freeze_brand_location,
          id_idremovereasonid: row.id_idremovereasonid,
          id_tissuesampletypeid: row.id_tissuesampletypeid,
          id_tissuetestid: row.id_tissuetestid,
          id_tissuesamplecontainertypeid: row.id_tissuesamplecontainertypeid,
          birth_type: row.birth_type,
          rear_type: row.rear_type,
          minimum_birth_weight: row.minimum_birth_weight,
          maximum_birth_weight: row.maximum_birth_weight,
          birth_weight_id_unitsid: row.birth_weight_id_unitsid,
          weight_id_unitsid: row.weight_id_unitsid,
          sale_price_id_unitsid: row.sale_price_id_unitsid,
          evaluation_update_alert: row.evaluation_update_alert,
          death_reason_id_contactid: row.death_reason_id_contactid,
          death_reason_id_companyid: row.death_reason_id_companyid,
          id_deathreasonid: row.id_deathreasonid,
          transfer_reason_id_contactid: row.transfer_reason_id_contactid,
          transfer_reason_id_companyid: row.transfer_reason_id_companyid,
          id_transferreasonid: row.id_transferreasonid,
        }));
  
        resolve(results);
      }
    });
  });
    
};