import { OwnerType } from "../../read/owners/ownerType";

export type WriteNewDefaultParameters = {
  default_settings_name: string;

  contactType: OwnerType;
  ownerId: string;
  owner_id_premiseid: string;

  breederType: OwnerType;
  breederId: string;
  breeder_id_premiseid: string;

  transferReasonContactType: OwnerType;
  transferReasonContactId: string;
  
  vet_id_contactid: string;
  vet_id_premiseid: string;
  lab_id_companyid: string;
  lab_id_premiseid: string;
  id_registry_id_companyid: string;
  registry_id_premiseid: string;
  id_stateid: string;
  id_countyid: string;
  id_flockprefixid: string;
  id_speciesid: string;
  id_breedid: string;
  id_sexid: string;
  id_idtypeid_primary: string;
  id_idtypeid_secondary: string;
  id_idtypeid_tertiary: string;
  id_eid_tag_male_color_female_color_same: string;
  eid_tag_color_male: string;
  eid_tag_color_female: string;
  eid_tag_location: string;
  id_farm_tag_male_color_female_color_same: string;
  farm_tag_based_on_eid_tag: string;
  farm_tag_number_digits_from_eid: string;
  farm_tag_color_male: string;
  farm_tag_color_female: string;
  farm_tag_location: string;
  id_fed_tag_male_color_female_color_same: string;
  fed_tag_color_male: string;
  fed_tag_color_female: string;
  fed_tag_location: string;
  id_nues_tag_male_color_female_color_same: string;
  nues_tag_color_male: string;
  nues_tag_color_female: string;
  nues_tag_location: string;
  id_trich_tag_male_color_female_color_same: string;
  trich_tag_color_male: string;
  trich_tag_color_female: string;
  trich_tag_location: string;
  trich_tag_auto_increment: string;
  trich_tag_next_tag_number: string;
  id_bangs_tag_male_color_female_color_same: string;
  bangs_tag_color_male: string;
  bangs_tag_color_female: string;
  bangs_tag_location: string;
  id_sale_order_tag_male_color_female_color_same: string;
  sale_order_tag_color_male: string;
  sale_order_tag_color_female: string;
  sale_order_tag_location: string;
  use_paint_marks: string;
  paint_mark_color: string;
  paint_mark_location: string;
  tattoo_color: string;
  tattoo_location: string;
  freeze_brand_location: string;
  id_idremovereasonid: string;
  id_tissuesampletypeid: string;
  id_tissuetestid: string;
  id_tissuesamplecontainertypeid: string;
  birth_type: string;
  rear_type: string;
  minimum_birth_weight: number;
  maximum_birth_weight: number;
  birth_weight_id_unitsid: string;
  weight_id_unitsid: string;
  sale_price_id_unitsid: string;
  evaluation_update_alert: string;
  death_reason_id_contactid: string;
  death_reason_id_companyid: string;
  id_deathreasonid: string;
  id_transferreasonid: string;
  created: string;
  modified: string;
}
